### ISSUE TITLE
Arty A7 35T - Etherbone/build error

### ISSUE THREAD

**Issue by cortez-daniel** [antmicro/rowhammer-tester#146]
Whenever I build the bitstream for the Arty-A7 35T I receive the warnings:

WARNING: [Synth 8-3331] design VexRiscv has unconnected port iBusWishbone_ERR
WARNING: [Synth 8-3331] design VexRiscv has unconnected port dBusWishbone_ERR
WARNING: [Synth 8-3331] design digilent_arty has unconnected port eth_rx_er
WARNING: [Synth 8-3331] design digilent_arty has unconnected port eth_col
WARNING: [Synth 8-3331] design digilent_arty has unconnected port eth_crs
Along with some other bit errors.

The bit stream generates and flashes to the device but the ethernet IP address is unreachable.
make srv does not connect and shows the error:
[CommUDP] ip: 192.168.100.50 / port: 1234 / tcp port: 1234
Traceback (most recent call last):
  File "/rowhammer-tester/venv/bin/litex_server", line 33, in <module>
    sys.exit(load_entry_point('litex', 'console_scripts', 'litex_server')())
  File "/rowhammer-tester/third_party/litex/litex/tools/litex_server.py", line 283, in main
    server.open()
  File "/rowhammer-tester/third_party/litex/litex/tools/litex_server.py", line 90, in open
    self.comm.open()
  File "/rowhammer-tester/third_party/litex/litex/tools/remote/comm_udp.py", line 33, in open
    self.probe(self.server, self.port)
  File "/rowhammer-tester/third_party/litex/litex/tools/remote/comm_udp.py", line 66, in probe
    raise Exception(f"Unable to probe Etherbone server at {self.server}.")
Exception: Unable to probe Etherbone server at 192.168.100.50.
make: *** [Makefile:81: srv] Error 1

Vivado Versions Tested: 2019.1, 2020.2, 2022.1

**Comment by cortez-daniel** [comment]
User error
